name: acephalous
recipe: drupal8
config:
  webroot: docroot
  php: '7.4'
  via: nginx
  drush: '^10'
  xdebug: true
services:
  appserver:
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
  database:
    type: 'mariadb:10.4'
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  mailhog:
    - mail.acephalous.lndo.site
tooling:
  robo:
    service: appserver
    description: Runs <robo> commands
    cmd: robo
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  blt:
    service: appserver
    cmd: /app/vendor/bin/blt
