<?php

/**
 * @file
 * Contains acephalous_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function acephalous_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the acephalous_rest module.
    case 'help.page.acephalous_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rest optmizations for Acephalous&#039;&#039;') . '</p>';
      return $output;

    default:
  }
}
